package onextent.bluecase.examples.ex1

import spray.json._

/**
   generated by aglio https://github.com/danielgtaylor/aglio with theme bluecase https://github.com/navicore/aglio-theme-bluecase
   with command:
       aglio -i ../../test/example3.md -t bluecase -o src/main/scala/onextent/bluecase/examples/ex1/TxnerStuff.scala --theme-super-class TxnerStuff --theme-collection-type List --theme-doubles 
*/

sealed abstract class TxnerStuff

case class Rule(code:Int) extends TxnerStuff

case class RuleHolder(code:Rule) extends TxnerStuff

case class Couponer(percent_off:Int, redeem_by:Int) extends TxnerStuff

case class Txner(coupon:Couponer, amt:Int, program:List[RuleHolder]) extends TxnerStuff

// json support

object RuleJsonProtocol extends DefaultJsonProtocol {
  implicit val ruleFormat = jsonFormat1(Rule)
} // Rule


object RuleHolderJsonProtocol extends DefaultJsonProtocol {
  implicit val ruleFormat = jsonFormat1(Rule)
  implicit val ruleHolderFormat = jsonFormat1(RuleHolder)
} // RuleHolder


object CouponerJsonProtocol extends DefaultJsonProtocol {
  implicit val couponerFormat = jsonFormat2(Couponer)
} // Couponer


object TxnerJsonProtocol extends DefaultJsonProtocol {
  implicit val couponerFormat = jsonFormat2(Couponer)
  implicit val ruleFormat = jsonFormat1(Rule)
  implicit val ruleHolderFormat = jsonFormat1(RuleHolder)
  implicit val txnerFormat = jsonFormat3(Txner)
} // Txner

