package onextent.bluecase.examples.ex1

import spray.json._

/**
   generated by aglio https://github.com/danielgtaylor/aglio with theme bluecase https://github.com/navicore/aglio-theme-bluecase
   with command:
       aglio -i ../../test/example2.md -t bluecase -o src/main/scala/onextent/bluecase/examples/ex1/TxnStuff.scala --theme-super-class TxnStuff --theme-collection-type List --theme-doubles 
*/

sealed abstract class TxnStuff

case class Couponed(percent_off:Int, redeem_by:Int) extends TxnStuff

case class Txn(coupon:Couponed, amt:Int) extends TxnStuff

// json support

object CouponedJsonProtocol extends DefaultJsonProtocol {
  implicit val couponedFormat = jsonFormat2(Couponed)
} // Couponed


object TxnJsonProtocol extends DefaultJsonProtocol {
  implicit val couponedFormat = jsonFormat2(Couponed)
  implicit val txnFormat = jsonFormat2(Txn)
} // Txn

